version: '3.7'
services:
 asesorias-microservicios:
  container_name: asesorias-core-sin-get
  image: oscarmantilla/asesorias-core-sin-get:1.0
  build:
   context: .
  ports:
   - 4000:4000
  networks:
   - asesorias-core-red
networks:
 asesorias-core-red: